Repository theonejonahgold/wat-zegt-deze-brief, pull requests merged in 2021-05, with the labels that each got.

#9 Add heroku procfiles
  .editorconfig
  .prettierignore
  .prettierrc
  back-end/Procfile
  back-end/package.json
  front-end/Procfile
  front-end/package.json
  front-end/src/hooks.ts
  front-end/svelte.config.js
  package-lock.json
Labels: miscellaneous

#12 Hotfix Heroku deployments
  back-end/package.json
  front-end/package.json
Labels: bug, miscellaneous

#41 Onboarding fe
  front-end/src/app.html
  front-end/src/lib/actions/index.ts
  front-end/src/lib/actions/textToSpeech.ts
  front-end/src/lib/components/atoms/Back.svelte
  front-end/src/lib/components/atoms/Button.svelte
  front-end/src/lib/components/atoms/Help.svelte
  front-end/src/lib/components/atoms/IconButton.svelte
  front-end/src/lib/components/atoms/NavItem.svelte
  front-end/src/lib/components/atoms/SpokenText.svelte
  front-end/src/lib/components/atoms/index.ts
  front-end/src/lib/components/molecules/Alert.svelte
  front-end/src/lib/components/molecules/ImageButton.svelte
  front-end/src/lib/components/molecules/Pagination.svelte
  front-end/src/lib/icons/ChatIcon.svelte
  front-end/src/lib/icons/LetterIcon.svelte
  front-end/src/lib/icons/ProfileIcon.svelte
  front-end/src/routes/__error.svelte
  front-end/src/routes/index.svelte
  front-end/src/routes/onboarding/__layout.reset.svelte
  front-end/src/routes/onboarding/index.svelte
  front-end/src/routes/onboarding/user/[step].json.ts
  front-end/src/routes/onboarding/user/index.svelte
  front-end/src/routes/onboarding/volunteer/[step].json.ts
  front-end/src/routes/onboarding/volunteer/index.svelte
  front-end/src/types/content.ts
  front-end/src/types/index.ts
  front-end/static/images/onboarding-user-1.png
  front-end/static/images/onboarding-user-2.png
  front-end/static/images/onboarding-user-3.png
  front-end/static/images/onboarding-user-4.png
  front-end/static/images/onboarding-user-5.png
  front-end/static/images/onboarding-volunteer-1.png
  front-end/static/images/onboarding-volunteer-2.png
  front-end/static/images/onboarding-volunteer-3.png
  front-end/static/images/onboarding-volunteer-4.png
  front-end/svelte.config.js
  front-end/tsconfig.json
  package-lock.json
Labels: enhancement, fe

#42 Create global styling and partially implement it
  front-end/package.json
  front-end/src/app.html
  front-end/src/app.scss
  front-end/src/lib/components/atoms/Back.svelte
  front-end/src/lib/components/atoms/Button.svelte
  front-end/src/lib/components/atoms/Help.svelte
  front-end/src/lib/components/atoms/Input.svelte
  front-end/src/lib/components/molecules/Field.svelte
  front-end/src/lib/components/molecules/Pagination.svelte
  front-end/src/lib/components/organisms/Form.svelte
  front-end/src/lib/components/organisms/Nav.svelte
  front-end/src/lib/components/templates/Register.svelte
  front-end/src/lib/components/templates/Success.svelte
  front-end/src/lib/components/templates/index.ts
  front-end/src/lib/config/env.ts
  front-end/src/routes/onboarding/__layout.reset.svelte
  front-end/src/routes/onboarding/user/register.svelte
  front-end/src/routes/onboarding/user/success.svelte
  front-end/src/routes/onboarding/volunteer/register.svelte
  front-end/src/routes/onboarding/volunteer/success.svelte
  front-end/svelte.config.js
  front-end/tsconfig.json
  package-lock.json
  package.json
Labels: enhancement, fe

#44 Text to speech
  front-end/src/lib/components/atoms/SpokenText.svelte
  front-end/src/lib/components/atoms/index.ts
  front-end/src/lib/components/molecules/Alert.svelte
  front-end/src/lib/components/molecules/ImageButton.svelte
  front-end/src/lib/icons/AudioIcon.svelte
  front-end/src/lib/icons/index.ts
  front-end/src/lib/utils/index.ts
  front-end/src/lib/utils/textToSpeech.ts
  front-end/src/routes/onboarding/index.svelte
Labels: enhancement, fe

#47 Sprint 0 finishing touches
  front-end/src/app.scss
  front-end/src/lib/components/atoms/Back.svelte
  front-end/src/lib/components/atoms/Icon.svelte
  front-end/src/lib/components/atoms/Image.svelte
  front-end/src/lib/components/atoms/Main.svelte
  front-end/src/lib/components/atoms/SpokenText.svelte
  front-end/src/lib/components/atoms/Title.svelte
  front-end/src/lib/components/atoms/index.ts
  front-end/src/lib/components/molecules/ImageButton.svelte
  front-end/src/lib/components/templates/Instructions.svelte
  front-end/src/lib/icons/AnchorIcon.svelte
  front-end/src/lib/icons/AudioIcon.svelte
  front-end/src/lib/icons/IndexIcon.svelte
  front-end/src/lib/icons/Oval.svelte
  front-end/src/lib/icons/UserIcon.svelte
  front-end/src/lib/icons/VolunteerIcon.svelte
  front-end/src/lib/types/form.ts
  front-end/src/lib/utils/textToSpeech.ts
  front-end/src/routes/dashboard/index.svelte
  front-end/src/routes/index.svelte
  front-end/src/routes/onboarding/index.svelte
  front-end/src/routes/userRole.svelte
  front-end/svelte.config.js
  front-end/tsconfig.json
Labels: enhancement, fe
